server:
  port: 8082



spring:
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      enable-auto-commit: false        # 手动签收
      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual                 # 手动签收
      concurrency: 5



###################################################################
# spring.kafka.consumer.auto-offset-reset
# 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
#
# latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
# earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
###################################################################