spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?userUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:tk/gushizone/**/dao/*.xml,classpath*:mapper/*.xml

logging:
  level:
    "tk.gushizone" : debug


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
