server:
  port: 8081

spring:
  datasource:
    # allowMultiQueries: 是否允许同时执行多条语句
    # rewriteBatchedStatements: 是否批量提交
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/demo?rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: redis

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false